SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

export PYTHONPATH="${REPO_ROOT}:${PYTHONPATH}"

# DATA_ROOT is only used as the prefix for relative paths in the CSV.
# The CSV files generated by build_csv.py all contain absolute paths.
# os.path.join(DATA_ROOT, "/abs") directly returns /abs, so this default value is not actually used for path joining.
# It can be overridden with an environment variable.
: "${DATA_ROOT:=/root/paddlejob/bosdata/yangfengyuan/ProcessedData}"

TRAIN_IMG_SIZE=960

CSV_NAME="infer_csv_long/out_csv/smoke_test_1row.csv"

PORT=23316
SEED=43
# Self-contained ONE-SHOT model directory. Users can set `export ONESHOT_MODEL_DIR=/path/...` to point to a local copy.
: "${ONESHOT_MODEL_DIR:=/root/paddlejob/bosdata/yangfengyuan/PretrainModels/Wan/ONESHOT-14B-diffusers}"
torchrun --nproc_per_node=1 --master_port=${PORT} tools/inference_long.py \
    --pretrain_path "${ONESHOT_MODEL_DIR}" \
    --train_data_root "${DATA_ROOT}" \
    --csv_path_name "${CSV_NAME}" \
    --test_image_size "${TRAIN_IMG_SIZE}" \
    --num_frames 81 \
    --save_path "${REPO_ROOT}/exp" \
    --scheduler "lcm" \
    --num_prevmotion_frames 5 \
    --num_inference_steps 4 \
    --seed ${SEED} \
    --num_extra_frames 0