SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

export PYTHONPATH="${REPO_ROOT}:${PYTHONPATH}"


# DATA_ROOT is only used as the prefix for relative paths in the CSV.
# The CSV files generated by build_csv.py in this repository all contain absolute paths.
# os.path.join(DATA_ROOT, "/abs") directly returns /abs, so this default value is not actually used for path joining.
# It can be overridden with an environment variable.
: "${DATA_ROOT:=/root/paddlejob/bosdata/yangfengyuan/ProcessedData}"

########## Inference resolution
TRAIN_IMG_SIZE=960

######## Inference data CSV
# Prefer the CSV_NAME environment variable from run_pipeline.sh; otherwise, use the default value below.
: "${CSV_NAME:=${REPO_ROOT}/Preprocessing/tmpout/out_scene_swap.csv}"

# Number of GPUs: default is 1; run_pipeline.sh automatically sets this according to the number of CSV rows.
: "${NPROC_PER_NODE:=1}"
: "${SEED:=42}"
# Self-contained ONE-SHOT model directory, including transformer / vae / text_encoder / tokenizer / scheduler / preprocess.
# Users can set `export ONESHOT_MODEL_DIR=/path/to/ONESHOT-14B-diffusers` to point to a local copy.
: "${ONESHOT_MODEL_DIR:=/root/paddlejob/bosdata/yangfengyuan/PretrainModels/Wan/ONESHOT-14B-diffusers}"


while p=$((RANDOM%10000+20000)); (exec 3<>/dev/tcp/127.0.0.1/$p) 2>/dev/null && exec 3<&- 3>&-; do :; done; MASTER_PORT=$p
torchrun --nproc_per_node=${NPROC_PER_NODE} --master_port=${MASTER_PORT} tools/inference_short.py \
    --pretrain_path "${ONESHOT_MODEL_DIR}" \
    --train_data_root "${DATA_ROOT}" \
    --csv_path_name "${CSV_NAME}" \
    --test_image_size "${TRAIN_IMG_SIZE}" \
    --num_frames 81 \
    --save_path "${REPO_ROOT}/exp" \
    --scheduler "lcm" \
    --num_inference_steps 4 \
    --seed ${SEED}